### ISSUE TITLE
update?

### ISSUE THREAD

**Issue by catalizcs** [almic/steam-js-api#2]
hi, im use this package for my project, but when start my project, this package send me this error:  { error: 'Request failed with status code 403.' }

**Comment by almic** [comment]
I apologize for replying over a year late, I've been doing other things. I will look back into this soon and see if I can get the API updated!

**Comment by RekratorCS** [comment]
ok :D

**Comment by almic** [comment]
It only took me half a year but hopefully now the errors are more descriptive of the issue you have. Hopefully, though, you already figured out the problem, lol.

I'm closing the issue now, but please reopen it and provide more information if you still have the issue!
